// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7earSJoOE3LG8XGP39v4fbk6VwUIeyg',
    appId: '1:965066458678:web:2a4db7e1ae77d7d491ba97',
    messagingSenderId: '965066458678',
    projectId: 'smart-printer-aac97',
    authDomain: 'smart-printer-aac97.firebaseapp.com',
    storageBucket: 'smart-printer-aac97.firebasestorage.app',
    measurementId: 'G-M75W16TNJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_IJdLA52awfOxyGxQOQplZejh5yD-ivk',
    appId: '1:965066458678:android:7d4bb039f0ef310091ba97',
    messagingSenderId: '965066458678',
    projectId: 'smart-printer-aac97',
    storageBucket: 'smart-printer-aac97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGHITbjtXRj8uGcQLEeigyaJKHk_NHgvM',
    appId: '1:965066458678:ios:5d4cacbca2df9cac91ba97',
    messagingSenderId: '965066458678',
    projectId: 'smart-printer-aac97',
    storageBucket: 'smart-printer-aac97.firebasestorage.app',
    iosBundleId: 'com.flavourhub.superprinter.superPrinter',
  );
}
